// Generated by Fukuro. Matches indicator text and file hashes only.
// It will also hit any file or message that merely mentions these values.
// Note: it.com is a shared or official domain, so no host string was generated for it.

rule Fukuro_Phish_Touch_n_Go_it_com_5d7ac8
{
    meta:
        description = "Phishing lure impersonating Touch 'n Go (qxxdaft.it.com)"
        author = "Fukuro"
        date = "2026-09-27"
        verdict = "malicious"
        impersonates = "Touch 'n Go"
        reference = "https://www.virustotal.com/gui/search/qxxdaft.it.com%2Fmoneypockett"
    strings:
        $p0 = "qxxdaft.it.com/moneypockett" ascii nocase
    condition:
        any of them
}
