// Generated by Fukuro. Matches indicator text and file hashes only.
// Domains match as whole hostnames: subdomains are included, lookalike domains are not.
// It will also hit any file or message that merely mentions these values.

rule Fukuro_Phish_Touch_n_Go_jkmss_a_sbs
{
    meta:
        description = "Phishing lure impersonating Touch 'n Go (jkmss-a.sbs)"
        author = "Fukuro"
        date = "2026-09-21"
        verdict = "malicious"
        impersonates = "Touch 'n Go"
        reference = "https://www.virustotal.com/gui/domain/jkmss-a.sbs"
    strings:
        $h0 = /(^|[^A-Za-z0-9-])jkmss-a\.sbs($|[^A-Za-z0-9.-]|\.($|[^A-Za-z0-9-]))/ nocase
        $p0 = "tng.jkmss-a.sbs/Rayamacam2.my7" ascii nocase
    condition:
        any of them
}
