// Generated by Fukuro. Matches indicator text and file hashes only.
// Domains match as whole hostnames: subdomains are included, lookalike domains are not.
// It will also hit any file or message that merely mentions these values.

rule Fukuro_Phish_Touch_n_Go_it_com
{
    meta:
        description = "Phishing lure impersonating Touch 'n Go (it.com)"
        author = "Fukuro"
        date = "2026-09-22"
        verdict = "malicious"
        impersonates = "Touch 'n Go"
        reference = "https://www.virustotal.com/gui/domain/it.com"
    strings:
        $h0 = /(^|[^A-Za-z0-9-])it\.com($|[^A-Za-z0-9.-]|\.($|[^A-Za-z0-9-]))/ nocase
        $p0 = "qxxdaft.it.com/moneypacketmp" ascii nocase
    condition:
        any of them
}
