// Generated by Fukuro. Matches indicator text and file hashes only.
// Domains match as whole hostnames: subdomains are included, lookalike domains are not.
// It will also hit any file or message that merely mentions these values.

rule Fukuro_Phish_Touch_n_Go_my_com_app
{
    meta:
        description = "Phishing lure impersonating Touch 'n Go (my-com.app)"
        author = "Fukuro"
        date = "2026-09-23"
        verdict = "malicious"
        impersonates = "Touch 'n Go"
        reference = "https://www.virustotal.com/gui/domain/my-com.app"
    strings:
        $h0 = /(^|[^A-Za-z0-9-])my-com\.app($|[^A-Za-z0-9.-]|\.($|[^A-Za-z0-9-]))/ nocase
    condition:
        any of them
}
