// Generated by Fukuro. Matches indicator text and file hashes only.
// Domains match as whole hostnames: subdomains are included, lookalike domains are not.
// It will also hit any file or message that merely mentions these values.

rule Fukuro_Phish_Touch_n_Go_m_oil_cyou
{
    meta:
        description = "Phishing lure impersonating Touch 'n Go (m-oil.cyou)"
        author = "Fukuro"
        date = "2026-09-25"
        verdict = "malicious"
        impersonates = "Touch 'n Go"
        reference = "https://www.virustotal.com/gui/domain/m-oil.cyou"
    strings:
        $h0 = /(^|[^A-Za-z0-9-])m-oil\.cyou($|[^A-Za-z0-9.-]|\.($|[^A-Za-z0-9-]))/ nocase
        $h1 = /(^|[^A-Za-z0-9-])my-tng\.link($|[^A-Za-z0-9.-]|\.($|[^A-Za-z0-9-]))/ nocase
        $p0 = "m-oil.cyou/moneypocket48" ascii nocase
    condition:
        any of them
}
