// Generated by Fukuro. Matches indicator text and file hashes only.
// Domains match as whole hostnames: subdomains are included, lookalike domains are not.
// It will also hit any file or message that merely mentions these values.

rule Fukuro_Phish_Touch_n_Go_touchngomalay_site
{
    meta:
        description = "Phishing lure impersonating Touch 'n Go (touchngomalay.site)"
        author = "Fukuro"
        date = "2026-10-07"
        verdict = "malicious"
        impersonates = "Touch 'n Go"
        reference = "https://www.virustotal.com/gui/domain/touchngomalay.site"
    strings:
        $h0 = /(^|[^A-Za-z0-9-])touchngomalay\.site($|[^A-Za-z0-9.-]|\.($|[^A-Za-z0-9-]))/ nocase
    condition:
        any of them
}
