// Generated by Fukuro. Matches indicator text and file hashes only.
// Domains match as whole hostnames: subdomains are included, lookalike domains are not.
// It will also hit any file or message that merely mentions these values.

rule Fukuro_Phish_Touch_n_Go_example_lure_test
{
    meta:
        description = "Phishing lure impersonating Touch 'n Go (example-lure.test)"
        author = "Fukuro"
        date = "2026-09-21"
        verdict = "malicious"
        impersonates = "Touch 'n Go"
        reference = "https://www.virustotal.com/gui/domain/example-lure.test"
    strings:
        $h0 = /(^|[^A-Za-z0-9-])example-lure\.test($|[^A-Za-z0-9.-]|\.($|[^A-Za-z0-9-]))/ nocase
        $p0 = "tng-verify.example-lure.test/login" ascii nocase
    condition:
        any of them
}
